-- MySQL Script generated by MySQL Workbench
-- Thu May 18 09:05:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RiverPass2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RiverPass2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RiverPass2` DEFAULT CHARACTER SET utf8 ;
USE `RiverPass2` ;

-- -----------------------------------------------------
-- Table `RiverPass2`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`Cliente` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `SobreNome` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `DataNasc` DATE NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiverPass2`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`Administrador` (
  `CPF` VARCHAR(9) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `SobreNome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `DataNasc` DATE NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Recebe_Pagamento_NumeroCartao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`, `Recebe_Pagamento_NumeroCartao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiverPass2`.`Destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`Destino` (
  `idDestino` INT NOT NULL,
  `Chegada` VARCHAR(45) NOT NULL,
  `Partida` VARCHAR(45) NOT NULL,
  `Rotas` VARCHAR(45) NOT NULL,
  `Administrador_CPF` VARCHAR(9) NOT NULL,
  `Administrador_Recebe_Pagamento_NumeroCartao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDestino`, `Administrador_Recebe_Pagamento_NumeroCartao`),
  INDEX `fk_Destino_Administrador1_idx` (`Administrador_CPF` ASC, `Administrador_Recebe_Pagamento_NumeroCartao` ASC),
  CONSTRAINT `fk_Destino_Administrador1`
    FOREIGN KEY (`Administrador_CPF` , `Administrador_Recebe_Pagamento_NumeroCartao`)
    REFERENCES `RiverPass2`.`Administrador` (`CPF` , `Recebe_Pagamento_NumeroCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiverPass2`.`Barco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`Barco` (
  `NumeroInscricao` VARCHAR(56) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Dono` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `NumeroPassageiros` VARCHAR(45) NOT NULL,
  `NumeroCamarote` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NumeroInscricao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiverPass2`.`barco_destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`barco_destino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_destino` INT NOT NULL,
  `barco_inscricao` VARCHAR(56) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_barco_destino_Destino1_idx` (`id_destino` ASC),
  INDEX `fk_barco_destino_Barco1_idx` (`barco_inscricao` ASC),
  CONSTRAINT `fk_barco_destino_Destino1`
    FOREIGN KEY (`id_destino`)
    REFERENCES `RiverPass2`.`Destino` (`idDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_barco_destino_Barco1`
    FOREIGN KEY (`barco_inscricao`)
    REFERENCES `RiverPass2`.`Barco` (`NumeroInscricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiverPass2`.`Passagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`Passagem` (
  `idPassagem` INT NOT NULL auto_increment,
  `DataViagem` DATE NOT NULL,
  `HoraViagem` TIME NOT NULL,
  `Valor` FLOAT NOT NULL,
  `NumeroPassagem` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `barco_destino_id` INT NOT NULL,
  PRIMARY KEY (`idPassagem`, `barco_destino_id`),
  INDEX `fk_Passagem_barco_destino1_idx` (`barco_destino_id` ASC),
  CONSTRAINT `fk_Passagem_barco_destino1`
    FOREIGN KEY (`barco_destino_id`)
    REFERENCES `RiverPass2`.`barco_destino` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiverPass2`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`banco` (
  `idbanco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiverPass2`.`contaBancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`contaBancaria` (
  `idcontaBancaria` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `agencia` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `banco_idbanco` INT NOT NULL,
  PRIMARY KEY (`idcontaBancaria`, `banco_idbanco`),
  INDEX `fk_contaBancaria_banco1_idx` (`banco_idbanco` ASC) ,
  CONSTRAINT `fk_contaBancaria_banco1`
    FOREIGN KEY (`banco_idbanco`)
    REFERENCES `RiverPass2`.`banco` (`idbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiverPass2`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RiverPass2`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_compra` DATE NOT NULL,
  `Cliente_CPF` INT NOT NULL,
  `Passagem_idPassagem` INT NOT NULL,
  `contaBancaria_idcontaBancaria` INT NOT NULL,
  `contaBancaria_banco_idbanco` INT NOT NULL,
  INDEX `fk_Cliente_has_Passagem_Passagem1_idx` (`Passagem_idPassagem` ASC),
  INDEX `fk_Cliente_has_Passagem_Cliente1_idx` (`Cliente_CPF` ASC),
  PRIMARY KEY (`id`, `contaBancaria_idcontaBancaria`, `contaBancaria_banco_idbanco`),
  INDEX `fk_compra_contaBancaria1_idx` (`contaBancaria_idcontaBancaria` ASC, `contaBancaria_banco_idbanco` ASC),
  CONSTRAINT `fk_Cliente_has_Passagem_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `RiverPass2`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Passagem_Passagem1`
    FOREIGN KEY (`Passagem_idPassagem`)
    REFERENCES `RiverPass2`.`Passagem` (`idPassagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_contaBancaria1`
    FOREIGN KEY (`contaBancaria_idcontaBancaria` , `contaBancaria_banco_idbanco`)
    REFERENCES `RiverPass2`.`contaBancaria` (`idcontaBancaria` , `banco_idbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

